### ISSUE TITLE
unable to require eye-slack

### ISSUE THREAD

**Issue by blackjid** [tmeinlschmidt/eye-slack#1]
I've been trying to add the slack notifications but I'm having this issue when I try to load the config.

```
cannot load such file -- eye/notify/slack
/usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/deploy/eye.d/notify.eye.rb:1:in `<top (required)>'
```

I tried just loading the gem on an irb console and this is what I'm getting

``` ruby
irb(main):001:0> require "eye/notify/slack"
NoMethodError: undefined method `underscore' for "Slack":String
    from /opt/rubies/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eye-0.6.4/lib/eye/notify.rb:94:in `register'
    from /opt/rubies/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eye-0.6.4/lib/eye/notify.rb:106:in `inherited'
    from /opt/rubies/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eye-slack-0.0.1/lib/eye/notify/slack/version.rb:6:in `<class:Notify>'
    from /opt/rubies/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eye-slack-0.0.1/lib/eye/notify/slack/version.rb:2:in `<module:Eye>'
    from /opt/rubies/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eye-slack-0.0.1/lib/eye/notify/slack/version.rb:1:in `<top (required)>'
    from /opt/rubies/2.0.0-p645/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/2.0.0-p645/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eye-slack-0.0.1/lib/eye/notify/slack.rb:2:in `<top (required)>'
    from /opt/rubies/2.0.0-p645/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /opt/rubies/2.0.0-p645/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /opt/rubies/2.0.0-p645/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from (irb):1
    from /opt/boxen/rbenv/versions/2.0.0/bin/irb:12:in `<main>'
irb(main):002:0>
```

thnks!

**Comment by tmeinlschmidt** [comment]
hey,

how did you added eye-slack to eye config?
did you quit eye and reload the config?

**Comment by blackjid** [comment]
mm, nop, I didn't quit eye to reload to config, I just reloaded it....
After quitting, it worked...

**Comment by blackjid** [comment]
thks!

**Comment by tmeinlschmidt** [comment]
glad it's working. seems I have to update readme :)
